"""
Driver script that runs the *known-objectives* clustering IO experiments
(``problem_fknown``) on the synthetic dataset produced by
``synthetic_instances.generate_synthetic_instances``.

It mirrors ``main_fknown.py`` (which uses the diet dataset via
``group_diet_instances.get_diet_instances``) but plugs the synthetic
generator in via ``synthetic_instances.to_diet_tuple``, as documented in
``README_synthetic.md``.

Run:

    python3 main_fknown_synthetic.py

Outputs (one pickle per configuration) are saved into
``./collecting outputs synthetic/``.
"""

from formulation_fknown import problem_fknown
from synthetic_instances import (
    generate_synthetic_instances,
    to_diet_tuple,
    solve_forward_problem,
)
import numpy as np
import time
import pandas as pd
import pickle
import auxfuncs as f
import os
from heuristic_fknown import heuristic, cluster_assignments


pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
np.set_printoptions(suppress=True)


# ---------------------------------------------------------------------------
#  Experiment configuration
# ---------------------------------------------------------------------------

N_test = 100
list_N = [100]
list_K = [5]
list_d = [20]
list_n_vars_perturbed = [1]#,0]      # 0 -> optimal decisions, 1 -> perturbed
list_L = [5, 8, 10, 12]             # number of clusters to try (true is 10)
list_interpretability = [False]     # set to True to plug in the catalogue
n_clusters_true = 10                # used by the synthetic generator
n_groups = 5                        # number of distinct b^n
m_core = 8                          # number of physical constraints in A_core
noise_concentration = 50.0          # tighter clusters when larger
timelimit = 3600.

OUTPUT_DIR = r"./collecting outputs synthetic"
os.makedirs(OUTPUT_DIR, exist_ok=True)


# ---------------------------------------------------------------------------
#  Main loop
# ---------------------------------------------------------------------------

for seed in [0, 1, 2]:
    for N in list_N:
        for K in list_K:
            for d in list_d:
                for n_vars_perturbed in list_n_vars_perturbed:

                    # ----------------------------------------------- data
                    print("DATA CONFIGURATION: (seed, N, K, d, n_vars_perturbed)=",
                          (seed, N, K, d, n_vars_perturbed))

                    # generate train + test instances jointly so that they
                    # share the same C, A and groups (but have different W
                    # and different perturbations)
                    perturbed = bool(n_vars_perturbed > 0)
                    synth = generate_synthetic_instances(
                        N=N + N_test,
                        K=K,
                        d=d,
                        m_core=m_core,
                        n_groups=n_groups,
                        n_clusters=n_clusters_true,
                        perturbed=perturbed,
                        n_vars_perturbed=n_vars_perturbed,
                        noise_concentration=noise_concentration,
                        seed=seed,
                        verbose=True,
                    )
                    instances = to_diet_tuple(synth)
                    (data, chosen_foods, list_of_objectives,
                     list_of_constraints, constraints, considered_groups,
                     C, W_orig, A, groups_N, list_bn, dataset) = instances

                    W_orig_train = W_orig[:N, :]
                    dataset_train = dataset[:N, :]
                    list_bn_train = list_bn[:N]
                    groups_N_train = groups_N[:N]

                    W_orig_test = W_orig[-N_test:, :]
                    dataset_test = dataset[-N_test:, :]
                    list_bn_test = list_bn[-N_test:]
                    groups_N_test = groups_N[-N_test:]

                    # ---------------------------- catalogue for interp mode
                    # the natural catalogue is the set of ground-truth
                    # cluster centroids generated by the synthetic data
                    predef_W_catalogue = synth["cluster_centroids"]

                    for L in list_L:

                        print("\n-------------\n")
                        print("NUMBER OF CLUSTERS REQUIRED L =", L)

                        name = str(("seed", seed,
                                    "N", N,
                                    "K", K,
                                    "d", d,
                                    "n_pert", n_vars_perturbed,
                                    "L", L))

                        for interpretability in list_interpretability:
                            print("INTERPRETABILITY: ", interpretability)

                            # ---------------- skip if already computed
                            already_done = np.any([
                                ('synth-fKNOWN-' + str(interpretability) + '-' + name) in s
                                for s in os.listdir(OUTPUT_DIR)
                            ])
                            if already_done:
                                print("ALREADY DONE -- SKIPPING")
                                continue

                            print("NOT ALREADY DONE")

                            # ---------------- predefined W and warmstart
                            if interpretability:
                                predef_W = predef_W_catalogue
                                warmstart = None
                                heur_outputs = None
                                obj_val_heur = None
                                best_iter = None
                                time_in_heur = None
                            else:
                                predef_W = None
                                inicio_heur = time.time()
                                heur_outputs, obj_val_heur, best_iter = heuristic(
                                    seed, C, N, L,
                                    dataset_train, A, list_bn_train,
                                    groups_N_train, considered_groups,
                                    init_type='optimal')
                                time_in_heur = time.time() - inicio_heur

                                W_heur, X_heur, u_heur, _, _ = f.regroup(
                                    heur_outputs[best_iter]['W'],
                                    np.abs(heur_outputs[best_iter]['X']),
                                    heur_outputs[best_iter]['u'])

                                print("Time in heuristic: ", time_in_heur)
                                print("Best heuristic iter: ", best_iter,
                                      ", obj val: ", obj_val_heur)
                                print("heuristic W:\n", W_heur.round(2))
                                print("heuristic X (col sums): ",
                                      X_heur.sum(axis=0))

                                warmstart = (X_heur, W_heur, u_heur)

                            # ---------------- exact solve
                            inicio = time.time()
                            output = problem_fknown(
                                C, N, L,
                                dataset_train, A, list_bn_train,
                                groups_N_train, considered_groups,
                                break_sym=False, linearize_product=False,
                                timelimit=timelimit, predef_W=predef_W,
                                warmstart=warmstart)
                            time_sol = time.time() - inicio

                            model, W, X, u, solution_log, progress_loss = output

                            print("time to sol: ", round(time_sol, 2), "s.")
                            gap = 0. if model.status == 2 else model.MIPGap * 100
                            obj_val_solver = model.objVal
                            print("objective val from solver: ",
                                  obj_val_solver, ", gap: ", gap)

                            try:
                                W_re, X_re, L_efective, delete_cluster = \
                                    f.regroup(W.X, X.X)
                            except Exception:
                                # used predef_W != None for interpretability
                                W_re, X_re, L_efective, delete_cluster = \
                                    f.regroup(W, X.X)

                            print("W:\n", np.round(W_re, 3))
                            print("cluster composition (sum X by cols): ",
                                  X_re.sum(axis=0))
                            print("efective number of clusters: ", L_efective)

                            # ---------------- TRAIN metrics
                            TRAIN_metrics = list(zip(*[
                                f.analyze_instance(
                                    W_orig_train[n, :],
                                    W_re[X_re[n, :].argmax(), :])
                                for n in range(N)]))
                            (TRAIN_equal_maxs, TRAIN_rmse, TRAIN_rho,
                             TRAIN_tau, TRAIN_cos_sim, TRAIN_emd) = TRAIN_metrics
                            (TRmean_equal_maxs, TRmean_rmse, TRmean_rho,
                             TRmean_tau, TRmean_cos_sim, TRmean_emd) = [
                                np.mean(m).round(3) for m in [
                                    TRAIN_equal_maxs, TRAIN_rmse, TRAIN_rho,
                                    TRAIN_tau, TRAIN_cos_sim, TRAIN_emd]]
                            print("MEAN TRAIN metrics "
                                  "(equal_maxs, rmse, rho, tau, cos_sim, emd):",
                                  TRmean_equal_maxs, TRmean_rmse, TRmean_rho,
                                  TRmean_tau, TRmean_cos_sim, TRmean_emd)

                            # ---------------- OUT-OF-SAMPLE evaluation
                            X_test, _ = cluster_assignments(
                                u.X, dataset_test, A, list_bn_test,
                                groups_N_test, considered_groups,
                                delete_cluster=delete_cluster)
                            clusters_test = [np.argmax(x) for x in X_test]

                            TEST_metrics = list(zip(*[
                                f.analyze_instance(
                                    W_orig_test[n, :],
                                    W_re[clusters_test[n], :])
                                for n in range(N_test)]))
                            (TEST_equal_maxs, TEST_rmse, TEST_rho,
                             TEST_tau, TEST_cos_sim, TEST_emd) = TEST_metrics
                            (TSmean_equal_maxs, TSmean_rmse, TSmean_rho,
                             TSmean_tau, TSmean_cos_sim, TSmean_emd) = [
                                np.mean(m).round(3) for m in [
                                    TEST_equal_maxs, TEST_rmse, TEST_rho,
                                    TEST_tau, TEST_cos_sim, TEST_emd]]
                            print("MEAN TEST metrics "
                                  "(equal_maxs, rmse, rho, tau, cos_sim, emd):",
                                  TSmean_equal_maxs, TSmean_rmse, TSmean_rho,
                                  TSmean_tau, TSmean_cos_sim, TSmean_emd)

                            # ---------------- instability comparison
                            comparison_instabs = {'real': [],
                                                  'estimated': [],
                                                  'dif': []}
                            for n in range(N):
                                W_s = {
                                    'estimated': W_re[X_re[n, :].argmax(), :],
                                    'real': W_orig_train[n, :]}
                                for vect in ['estimated', 'real']:
                                    W_chosen = W_s[vect]
                                    linear_obj = W_chosen @ C
                                    z_star = solve_forward_problem(
                                        linear_obj, A, list_bn_train[n],
                                        n_vars_perturbed=0)
                                    inst = linear_obj @ (
                                        dataset_train[n, :] - z_star)
                                    comparison_instabs[vect].append(inst)
                                comparison_instabs['dif'].append(
                                    comparison_instabs['real'][-1]
                                    - comparison_instabs['estimated'][-1])
                            print("TRAIN real - estimated instab (mean,std):",
                                  (np.mean(comparison_instabs['dif']),
                                   np.std(comparison_instabs['dif'])))

                            TEST_comparison_instabs = {'real': [],
                                                       'estimated': [],
                                                       'dif': []}
                            for n in range(N_test):
                                W_s = {
                                    'estimated': W_re[clusters_test[n], :],
                                    'real': W_orig_test[n, :]}
                                for vect in ['estimated', 'real']:
                                    W_chosen = W_s[vect]
                                    linear_obj = W_chosen @ C
                                    z_star = solve_forward_problem(
                                        linear_obj, A, list_bn_test[n],
                                        n_vars_perturbed=0)
                                    inst = linear_obj @ (
                                        dataset_test[n, :] - z_star)
                                    TEST_comparison_instabs[vect].append(inst)
                                TEST_comparison_instabs['dif'].append(
                                    TEST_comparison_instabs['real'][-1]
                                    - TEST_comparison_instabs['estimated'][-1])
                            print("TEST  real - estimated instab (mean,std):",
                                  (np.mean(TEST_comparison_instabs['dif']),
                                   np.std(TEST_comparison_instabs['dif'])))

                            # ---------------- save
                            sol_outputs = {
                                'seed': seed,
                                'N': N,
                                'n_vars_perturbed': n_vars_perturbed,
                                'perturbed': perturbed,
                                'instances': instances,
                                'synthetic_meta': {
                                    'cluster_centroids':
                                        synth['cluster_centroids'],
                                    'cluster_assignments_train':
                                        synth['cluster_assignments'][:N],
                                    'cluster_assignments_test':
                                        synth['cluster_assignments'][-N_test:],
                                    'n_clusters_true': n_clusters_true,
                                    'n_groups': n_groups,
                                    'm_core': m_core,
                                    'noise_concentration': noise_concentration,
                                },
                                'K': K,
                                'd': d,
                                'interpretability': interpretability,
                                'L': L,
                                'heuristic': heur_outputs,
                                'best_obj_val': obj_val_heur,
                                'best_iter': best_iter,
                                'time_in_heur': time_in_heur,
                                'warmstart': warmstart,
                                'optimality': model.status == 2,
                                'time': round(time_sol, 3),
                                'gap': gap,
                                'solution_log': solution_log,
                                'progress_loss': progress_loss,
                                'obj_val': obj_val_solver,
                                'print_W': str(W_re.round(2)),
                                'W': np.round(W_re, 3),
                                'X': X_re.astype(int),
                                'X_composition': X_re.sum(axis=0),
                                'L_efective': L_efective,
                                'delete_clusters': delete_cluster,
                                'clusters_test': clusters_test,
                                'TRcomparison_instabs': comparison_instabs,
                                'TRcomparison_instabs_mean':
                                    np.mean(comparison_instabs['dif']),
                                'TRAIN_metrics': TRAIN_metrics,
                                'TRmean_equal_maxs': TRmean_equal_maxs,
                                'TRmean_rmse': TRmean_rmse,
                                'TRmean_rho': TRmean_rho,
                                'TRmean_tau': TRmean_tau,
                                'TRmean_cos_sim': TRmean_cos_sim,
                                'TRmean_emd': TRmean_emd,
                                'TScomparison_instabs': TEST_comparison_instabs,
                                'TScomparison_instabs_mean':
                                    np.mean(TEST_comparison_instabs['dif']),
                                'TEST_metrics': TEST_metrics,
                                'TSmean_equal_maxs': TSmean_equal_maxs,
                                'TSmean_rmse': TSmean_rmse,
                                'TSmean_rho': TSmean_rho,
                                'TSmean_tau': TSmean_tau,
                                'TSmean_cos_sim': TSmean_cos_sim,
                                'TSmean_emd': TSmean_emd,
                            }

                            fname = os.path.join(
                                OUTPUT_DIR,
                                'synth-fKNOWN-' + str(interpretability)
                                + '-' + name + '.pkl')
                            with open(fname, 'wb') as handle:
                                pickle.dump(sol_outputs, handle,
                                            protocol=pickle.HIGHEST_PROTOCOL)
                            print("Saved:", fname)
