"""
Synthetic data generator for the Inverse Multiobjective Optimization
clustering experiments described in the paper

    "Preference estimation in inverse multiobjective optimization"

This module mimics ``group_diet_instances.get_diet_instances`` but builds the
forward optimization problem from scratch (no Excel file required), so that
controlled stress tests with arbitrary K, d, N and number of clusters can be
performed.

Design summary (defaults match the requirements of the paper revision):

    * K = 5 linear objectives, each pointing in a different direction in
      R^d (d = 20).  Vectors are first generated as iid Gaussian, then
      orthogonalized via Gram-Schmidt and finally L1-normalized so that
      ||c^k||_1 = 1 -- the same convention used in the diet experiments.

    * N = 100 instances.  The feasible region of every instance is

            A z >= b^{n}        0 <= z <= z_max

      where the matrix A in R^{m x d} is shared by all instances and only
      the right-hand side b^{n} changes.  We build n_groups=5 different
      right-hand sides {b^1,...,b^5} (the analog of the five demographic
      groups in the diet problem) and assign each instance to one of them.

    * Preferences are drawn around n_clusters=10 centroids on the K-simplex
      via a Dirichlet noise model.  Each centroid is a sparse weight vector
      that emphasises one or two of the objectives (matching the catalogue
      \tilde{W} described in Appendix 8.3 of the paper).

    * A boolean flag ``perturbed`` decides whether the dataset contains
      genuinely optimal solutions (``perturbed=False``) or sub-optimal ones
      generated by forcing ``n_vars_perturbed`` randomly chosen variables
      to be >= 1 (``perturbed=True``), exactly as in
      ``group_diet_instances.original_problem``.

The function returns a dictionary with all the building blocks plus a tuple
that follows the same field order as ``get_diet_instances`` so the script
can be plugged into ``main_fknown.py`` / ``main_fUNknown.py`` with minimal
changes (see README_synthetic.md for a usage example).
"""

from __future__ import annotations

import os
import pickle
import random
from typing import Optional

import numpy as np
import gurobipy as gp
from sklearn.metrics.pairwise import cosine_similarity


np.set_printoptions(suppress=True)


# ---------------------------------------------------------------------------
#  Forward optimization problem (single instance)
# ---------------------------------------------------------------------------

def solve_forward_problem(linear_obj: np.ndarray,
                          A: np.ndarray,
                          b: np.ndarray,
                          n_vars_perturbed: int = 0,
                          z_max: float = 2.0,
                          perturb_lb: float = 1.0) -> Optional[np.ndarray]:
    """
    Solve

            min_z   linear_obj @ z
            s.t.    A z <= b              (note: A and b are stacked so that
                                           A z >= b_orig becomes -A z <= -b_orig)
                    0 <= z <= z_max

    If ``n_vars_perturbed > 0`` then exactly ``n_vars_perturbed`` randomly
    chosen variables are forced to have a lower bound of ``perturb_lb`` (1.0
    by default).  This is the suboptimal-decision protocol described in
    Section 6 of the paper.

    Returns the optimal z (numpy array of size d) or None if infeasible.
    """

    m, d = A.shape

    model_n = gp.Model()
    model_n.setParam('OutputFlag', 0)

    lb = np.zeros(d)
    if n_vars_perturbed > 0:
        for j in random.sample(list(range(d)), n_vars_perturbed):
            lb[j] = perturb_lb

    z = model_n.addMVar(shape=d,
                        lb=lb,
                        ub=z_max,
                        vtype=gp.GRB.CONTINUOUS,
                        name="z")

    model_n.setObjective(linear_obj @ z, sense=gp.GRB.MINIMIZE)
    model_n.addConstr(A @ z <= b)
    model_n.update()
    model_n.optimize()

    if model_n.status == gp.GRB.OPTIMAL:
        return z.X
    return None


# ---------------------------------------------------------------------------
#  Building blocks
# ---------------------------------------------------------------------------

def _build_objectives(K: int,
                      d: int,
                      min_pairwise_cos: float = 0.6) -> np.ndarray:
    """
    Generate ``K`` cost vectors in R^d that point in clearly different
    directions.

    Strategy
    --------
    1. Sample K iid Gaussian vectors.
    2. Apply Gram-Schmidt to orthogonalize them (cos sim of the orthogonal
       directions is exactly zero).
    3. Add a small (sign-aware) random shift so that the vectors are not
       perfectly orthogonal -- otherwise every objective would be balanced
       and Gram-Schmidt artefacts would dominate.  We control the maximum
       allowed pairwise cosine similarity via ``min_pairwise_cos`` (defaults
       to 0.6, i.e. directions are guaranteed to differ by at least
       ~53 degrees).
    4. L1-normalize: ``||c^k||_1 = 1``.
    """

    while True:
        G = np.random.randn(K, d)
        # Gram-Schmidt
        Q = np.zeros_like(G)
        for k in range(K):
            v = G[k].copy()
            for j in range(k):
                v -= (v @ Q[j]) * Q[j]
            n = np.linalg.norm(v)
            if n < 1e-9:
                break
            Q[k] = v / n
        else:
            # add a small random component so the vectors are not perfectly
            # orthogonal but still well separated
            C = Q + 0.1 * np.random.randn(K, d)
            C = np.array([c / np.abs(c).sum() for c in C])

            # accept only if every pair of directions has |cos sim| <=
            # min_pairwise_cos -- guarantees objectives are diverse
            ok = True
            for i in range(K - 1):
                for j in range(i + 1, K):
                    cs = cosine_similarity(C[i].reshape(1, -1),
                                           C[j].reshape(1, -1))[0][0]
                    if abs(cs) > min_pairwise_cos:
                        ok = False
                        break
                if not ok:
                    break
            if ok:
                return C
        # else loop and try again


def _build_constraints(d: int,
                       m_core: int,
                       n_groups: int,
                       z_max: float = 2.0):
    """
    Build the shared constraint matrix A and the ``n_groups`` right-hand
    sides b^{n}.

    The "physical" constraint is

            A_core @ z >= b_core^{n}            (lower bounds on m_core
                                                 linear functions of z)
            0 <= z <= z_max                     (box on the variables)

    which is rewritten into the canonical form A z <= b used by
    ``solve_forward_problem``:

            A = [-A_core ;  -I_d ;  I_d]
            b = [-b_core^{n} ;  0  ;  z_max * 1_d]
    """

    # core matrix: nonneg entries (analog of nutritional values).  Using a
    # uniform U(0.1, 2.0) keeps the LP well-conditioned.
    A_core = np.random.uniform(0.1, 2.0, size=(m_core, d))

    # we want every b_core to be feasible: choose it as a fraction of
    # A_core @ (z_max * 1) so the LP is non-trivial yet always feasible
    max_lhs = A_core @ (z_max * np.ones(d))   # (m_core,)
    b_core_list = []
    for _ in range(n_groups):
        # fraction in [0.2, 0.7] of the max feasible LHS, jittered per row
        frac = np.random.uniform(0.2, 0.7, size=m_core)
        b_core_list.append(frac * max_lhs)

    # build canonical form
    A_canonical = np.concatenate([-A_core,
                                  -np.eye(d),
                                  np.eye(d)], axis=0)
    b_canonical_list = [
        np.concatenate([-b_core, np.zeros(d), z_max * np.ones(d)])
        for b_core in b_core_list
    ]

    return A_core, A_canonical, b_core_list, b_canonical_list


def _build_cluster_centroids(K: int,
                             n_clusters: int) -> np.ndarray:
    """
    Build ``n_clusters`` weight centroids on the K-simplex.

    The first K centroids are the canonical basis vectors (one per
    objective: "minimize objective k only").  Remaining centroids are sparse
    combinations -- balanced pairs and triples -- following the same logic
    as the catalogue \tilde{W} in Appendix 8.3 of the paper.
    """

    centroids = []

    # 1) one-hot centroids -- emphasise a single objective
    for k in range(min(K, n_clusters)):
        e = np.zeros(K)
        e[k] = 1.0
        centroids.append(e)

    # 2) balanced pairs of objectives (50/50)
    if len(centroids) < n_clusters:
        for k1 in range(K):
            for k2 in range(k1 + 1, K):
                if len(centroids) >= n_clusters:
                    break
                w = np.zeros(K)
                w[k1] = w[k2] = 0.5
                centroids.append(w)
            if len(centroids) >= n_clusters:
                break

    # 3) unbalanced pairs (75/25)
    if len(centroids) < n_clusters:
        for k1 in range(K):
            for k2 in range(K):
                if k1 == k2 or len(centroids) >= n_clusters:
                    continue
                w = np.zeros(K)
                w[k1] = 0.75
                w[k2] = 0.25
                centroids.append(w)
            if len(centroids) >= n_clusters:
                break

    # 4) uniform centroid as a last resort
    if len(centroids) < n_clusters:
        centroids.append(np.ones(K) / K)

    centroids = np.array(centroids[:n_clusters])
    return centroids


def _build_weights(N: int,
                   K: int,
                   n_clusters: int,
                   noise_concentration: float = 50.0):
    """
    Draw N preference vectors clustered around ``n_clusters`` centroids.

    For each instance we
        1. uniformly choose a cluster index ``ell``,
        2. draw a Dirichlet sample with concentration alpha = ``noise_concentration``
           * (centroid + epsilon), ensuring strictly positive parameters.

    Larger ``noise_concentration`` -> tighter clusters (less noise).
    """

    centroids = _build_cluster_centroids(K, n_clusters)
    eps = 1e-2  # avoid zero Dirichlet parameters

    cluster_assignments = np.random.choice(n_clusters, size=N)
    W = np.zeros((N, K))
    for n in range(N):
        ell = cluster_assignments[n]
        alpha = noise_concentration * (centroids[ell] + eps)
        W[n, :] = np.random.dirichlet(alpha)
    return W, centroids, cluster_assignments


# ---------------------------------------------------------------------------
#  Main API
# ---------------------------------------------------------------------------

def generate_synthetic_instances(N: int = 100,
                                 K: int = 5,
                                 d: int = 20,
                                 m_core: int = 8,
                                 n_groups: int = 5,
                                 n_clusters: int = 10,
                                 perturbed: bool = True,
                                 n_vars_perturbed: int = 1,
                                 noise_concentration: float = 50.0,
                                 z_max: float = 2.0,
                                 perturb_lb: float = 1.0,
                                 min_pairwise_cos: float = 0.6,
                                 seed: int = 0,
                                 verbose: bool = True):
    """
    Generate a synthetic dataset for the inverse multiobjective optimization
    clustering experiments.

    Parameters
    ----------
    N : int
        Number of instances.
    K : int
        Number of objectives (default 5).
    d : int
        Dimension of the decision variable z (default 20).
    m_core : int
        Number of "physical" constraints (rows of A_core, before adding box
        constraints).
    n_groups : int
        Number of distinct right-hand sides b^{n} (default 5).
    n_clusters : int
        Number of preference clusters (default 10).
    perturbed : bool
        If True the dataset contains sub-optimal decisions obtained by
        forcing ``n_vars_perturbed`` randomly selected variables to be >= 1
        before solving the LP.  If False the LP is solved as-is (genuinely
        optimal decisions).
    n_vars_perturbed : int
        Number of variables to perturb per instance (only used when
        ``perturbed`` is True).
    noise_concentration : float
        Dirichlet concentration around each centroid; larger -> tighter
        clusters.
    z_max : float
        Upper bound on every component of z.
    perturb_lb : float
        Lower bound applied to perturbed variables.
    min_pairwise_cos : float
        Maximum |cos sim| allowed between any two cost vectors.
    seed : int
        Random seed for reproducibility.
    verbose : bool
        Print diagnostics.

    Returns
    -------
    dict
        Contains every building block of the dataset (see README).
    """

    np.random.seed(seed)
    random.seed(seed)

    if verbose:
        print(f"\n=== generate_synthetic_instances ===")
        print(f"  seed={seed}  N={N}  K={K}  d={d}  m_core={m_core}")
        print(f"  n_groups={n_groups}  n_clusters={n_clusters}")
        print(f"  perturbed={perturbed}  n_vars_perturbed={n_vars_perturbed}")
        print(f"  noise_concentration={noise_concentration}\n")

    # ------------------------------------------------------------------ C
    C = _build_objectives(K, d, min_pairwise_cos=min_pairwise_cos)
    if verbose:
        print("Objective vectors (C) cosine similarities:")
        for i in range(K - 1):
            for j in range(i + 1, K):
                cs = cosine_similarity(C[i].reshape(1, -1),
                                       C[j].reshape(1, -1))[0][0]
                print(f"  c^{i+1} vs c^{j+1}: {cs:+.3f}")

    # --------------------------------------------------------------- A, b
    A_core, A, b_core_list, b_canonical_list = _build_constraints(
        d=d, m_core=m_core, n_groups=n_groups, z_max=z_max)

    considered_groups = [f"group_{g}" for g in range(n_groups)]

    # assign each instance to one of the groups
    groups_N = [random.choice(considered_groups) for _ in range(N)]

    def _b_for(group_name: str) -> np.ndarray:
        return b_canonical_list[considered_groups.index(group_name)]

    list_bn = [_b_for(g) for g in groups_N]

    # ------------------------------------------------------------------ W
    W, centroids, cluster_assignments = _build_weights(
        N=N, K=K, n_clusters=n_clusters,
        noise_concentration=noise_concentration)

    if verbose:
        print("\nCluster centroids (rows = clusters):")
        print(centroids.round(3))
        print(f"\nW (first 5 instances):\n{W[:5].round(3)}")
        print(f"W mean: {W.mean(axis=0).round(3)}")
        print(f"W std : {W.std(axis=0).round(3)}")

    # --------------------------------------------------- forward solutions
    n_pert_used = n_vars_perturbed if perturbed else 0

    linear_objs = W @ C            # (N, d)
    dataset = np.zeros((N, d))
    for n in range(N):
        attempts = 0
        z = None
        while z is None and attempts < 50:
            z = solve_forward_problem(linear_objs[n, :],
                                      A,
                                      list_bn[n],
                                      n_vars_perturbed=n_pert_used,
                                      z_max=z_max,
                                      perturb_lb=perturb_lb)
            attempts += 1
        if z is None:
            raise RuntimeError(
                f"Failed to solve instance n={n} after 50 attempts. "
                f"Try lowering perturb_lb or n_vars_perturbed.")
        dataset[n, :] = z

    if verbose:
        print(f"\nDataset shape: {dataset.shape}")
        print(f"Dataset mean: {dataset.mean(axis=0).round(3)}")
        print(f"Dataset std : {dataset.std(axis=0).round(3)}")
        print(f"Group composition: "
              f"{ {g: groups_N.count(g) for g in considered_groups} }")
        cluster_sizes = np.bincount(cluster_assignments, minlength=n_clusters)
        print(f"Cluster composition: {cluster_sizes.tolist()}")

    return {
        # objectives
        "C": C,                              # (K, d) cost matrix
        "list_of_objectives": [f"obj_{k}" for k in range(K)],

        # constraints
        "A_core": A_core,                    # (m_core, d)
        "A": A,                              # (m_core + 2d, d) canonical
        "b_core_list": b_core_list,          # list of n_groups arrays
        "list_bn": list_bn,                  # length N (canonical RHS)
        "considered_groups": considered_groups,
        "groups_N": groups_N,                # length N
        "list_of_constraints": [f"constraint_{i}" for i in range(m_core)],

        # preferences
        "W": W,                              # (N, K)
        "cluster_centroids": centroids,      # (n_clusters, K)
        "cluster_assignments": cluster_assignments,  # (N,)

        # decisions
        "dataset": dataset,                  # (N, d)

        # metadata
        "perturbed": perturbed,
        "n_vars_perturbed": n_pert_used,
        "z_max": z_max,
        "seed": seed,
    }


def to_diet_tuple(synthetic: dict):
    """
    Convert the dictionary returned by ``generate_synthetic_instances`` into
    a tuple with the same field order as ``get_diet_instances`` so that
    ``main_fUNknown.py`` / ``main_fknown.py`` can use it as a drop-in
    replacement::

        data, chosen_foods, list_of_objectives, list_of_constraints,
        constraints, considered_groups, C, W, A, groups_N, list_bn, dataset
            = to_diet_tuple(synthetic)

    Fields that have no synthetic analog (``data``, ``chosen_foods``,
    ``constraints``) are returned as ``None``.
    """

    return (
        None,                                 # data (DataFrame in diet)
        None,                                 # chosen_foods
        synthetic["list_of_objectives"],
        synthetic["list_of_constraints"],
        None,                                 # constraints (DataFrame in diet)
        synthetic["considered_groups"],
        synthetic["C"],
        synthetic["W"],
        synthetic["A"],
        synthetic["groups_N"],
        synthetic["list_bn"],
        synthetic["dataset"],
    )


# ---------------------------------------------------------------------------
#  Script entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":

    out_dir = "synthetic_data"
    os.makedirs(out_dir, exist_ok=True)

    seed = 2

    for perturbed in [True]:
        synth = generate_synthetic_instances(
            N=100,
            K=5,
            d=20,
            m_core=8,
            n_groups=5,
            n_clusters=10,
            perturbed=perturbed,
            n_vars_perturbed=1,
            noise_concentration=50.0,
            seed=seed,
            verbose=True,
        )

        suffix = "perturbed" if perturbed else "optimal"
        fname = os.path.join(
            out_dir,
            f"synthetic_K5_d20_N100_clusters10_{suffix}_seed_{seed}.pkl")
        with open(fname, "wb") as f:
            pickle.dump(synth, f, protocol=pickle.HIGHEST_PROTOCOL)
        print(f"\nSaved: {fname}\n")
